PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX cit: <http://culture-in-time.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

select distinct (sample(?l_lowercase) as ?l_sample) ?ps (count(distinct ?uri) as ?count) 
where {
    {
        ?uri ?p ?o .
        filter(contains(str(?p),"/prop/direct/P"))
        bind(?p as ?ps)
    }
    UNION
    {
        OPTIONAL {
            << ?uri ?p ?o >> ?a ?b .
        }
        filter(contains(str(?a),"/prop/qualifier/P"))
        bind(?a as ?ps)
    }
     UNION
    {
        OPTIONAL {
            << ?uri ?p ?o >>  <http://www.w3.org/ns/prov#wasDerivedFrom> ?b .
            ?b ?ref_prop ?ref_obj
        }
       
        bind(?ref_prop as ?ps)
    }
    
    ?ps rdfs:label ?l .
    filter(lang(?l) = "en")

    bind(lcase(?l) as ?l_lowercase)
    {
         <spotlight_query_placeholder> a "triple"
    }
} 
group by ?ps 
order by DESC(?count) ?l_sample
