PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit: <http://culture-in-time.org/ontology/>

construct 
{
   ?uri ?p ?o .
   ?o rdfs:label ?label .
    << ?uri ?p ?o >> ?qual ?qual_obj .
}

where {
    values ?uri { <uri_values_placeholder> }
    values ?p { <forward_prop_values_placeholder> }
    values ?qual { <qualifier_prop_values_placeholder> }
    values ?lang { "en" "de" }
    ?uri ?p ?o .
    ?o rdfs:label ?label .
    filter(lang(?label) = ?lang)
    OPTIONAL {
       << ?uri ?p ?o >> ?qual ?qual_obj .
        OPTIONAL {
             ?qual_obj rdfs:label ?qual_label .
       		 filter(lang(?qual_label) = ?lang) 
        }
    }
}