PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX onto: <http://www.ontotext.com/>

CONSTRUCT {
  ?o ?p ?s  .
  ?p rdfs:label ?prop_label .
  ?s rdfs:label ?sub_label .
  ?o rdfs:label ?obj_label .
  
}
WHERE {
  {
    select * where {
      values ?o { <entity_uri_placeholder> }
        ?s ?p ?o  .
        filter(contains(str(?p),"/prop/direct/P"))
    } limit 200
  }
  
  OPTIONAL {
    ?s rdfs:label ?sub_label .
    values ?langs  {"languages_placeholder" }
    filter(lang(?sub_label) = ?langs)
  }
  OPTIONAL {
    ?p rdfs:label ?prop_label .
     values ?langs  {"languages_placeholder" }
    filter(lang(?prop_label) = ?langs)
  }

  OPTIONAL {
    ?o rdfs:label ?obj_label .
    values ?langs  {"languages_placeholder" }
    filter(lang(?obj_label) = ?langs)
  }

}