PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX schema: <http://schema.org/>
PREFIX cit: <http://culture-in-time.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>

select ?uri (sample(?t) as ?title) (sample(?d) as ?description) (sample(?p) as ?place) (sample(?c) as ?country) ?startDate  ?image
FROM onto:disable-sameAs
where {
    ?uri   cit:title ?t .
    OPTIONAL {
        ?uri cit:startDate ?startDate .
    }
    OPTIONAL {
        ?uri cit:description ?d .
    }
    OPTIONAL {
        ?uri cit:placeName ?p .
    }
    OPTIONAL {
        ?uri cit:placeCountryName ?c .
    }
    OPTIONAL {
        ?uri cit:image ?image .
    }
    {
       <spotlight_query_placeholder> a "triple"
    }
} group by ?startDate ?uri ?image
order by ?startDate